### Recuperar los usuarios
GET http://localhost:3000/api/usuarios
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2RjMTUzMTI4MDYxYzAyNWM1ZWU5YzgiLCJpYXQiOjE2NzUzNzcwMjYsImV4cCI6MTY3NTQyMDIyNn0.R5xpCjQHToK4mvAgtNC5OqB_6KO_RDY6c_TSSiWtYqs


### Crear usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre": "pedro hernandez",
    "email": "pedro.h@gmail.com",
    "password": "1234"
}

### Recuperar un usuario
GET http://localhost:3000/api/usuarios/63d82815d13b0e6d54e76839


### Actualizar un usuario
PUT http://localhost:3000/api/usuarios/63dc153128061c025c5ee9c8
Content-Type: application/json

{
    "nombre": "pedro p. hernandez",
    "email": "pedro.h@gmail.com",
    "role": "USER_ROLE"
}

### Eliminar un usuario
DELETE http://localhost:3000/api/usuarios/63d82815d13b0e6d54e76839


### login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "pedro.h@gmail.com",
    "password": "1234"
}

### Recuperar los academias
GET http://localhost:3000/api/academias
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2RjMTUzMTI4MDYxYzAyNWM1ZWU5YzgiLCJpYXQiOjE2NzU2NDQ5NzYsImV4cCI6MTY3NTY4ODE3Nn0.6PllQgH1N6kSyHSuF7_CDUXQ7Q35OUohIMzwgtIeSjs


### Crear academia
POST http://localhost:3000/api/academias
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UwNTQ4NjAwMDI3YzczMDdmZmNmM2MiLCJpYXQiOjE2NzU2NDYxMDIsImV4cCI6MTY3NTY4OTMwMn0.sLFjqpID7KqxeeTpkJa5KrbrWPMHbbKaT4QcG0WdOfw
Content-Type: application/json

{
    "nombre": "Academia Buin",
    "direccion": "Condel 789, Buin"
}

### Recuperar los niveles
GET http://localhost:3000/api/niveles
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2RjMTUzMTI4MDYxYzAyNWM1ZWU5YzgiLCJpYXQiOjE2NzU2NDQ5NzYsImV4cCI6MTY3NTY4ODE3Nn0.6PllQgH1N6kSyHSuF7_CDUXQ7Q35OUohIMzwgtIeSjs


### Crear niveles
POST http://localhost:3000/api/niveles
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UwNTQ4NjAwMDI3YzczMDdmZmNmM2MiLCJpYXQiOjE2NzU2NDYxMDIsImV4cCI6MTY3NTY4OTMwMn0.sLFjqpID7KqxeeTpkJa5KrbrWPMHbbKaT4QcG0WdOfw
Content-Type: application/json

{
    "nombre": "Camuflado",
    "orden": 7
}


### Recuperar los categorias
GET http://localhost:3000/api/categorias
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2RjMTUzMTI4MDYxYzAyNWM1ZWU5YzgiLCJpYXQiOjE2NzU2NDQ5NzYsImV4cCI6MTY3NTY4ODE3Nn0.6PllQgH1N6kSyHSuF7_CDUXQ7Q35OUohIMzwgtIeSjs


### Crear categorias
POST http://localhost:3000/api/categorias
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UwNTQ4NjAwMDI3YzczMDdmZmNmM2MiLCJpYXQiOjE2NzU2NDYxMDIsImV4cCI6MTY3NTY4OTMwMn0.sLFjqpID7KqxeeTpkJa5KrbrWPMHbbKaT4QcG0WdOfw
Content-Type: application/json

{
    "nombre": "Warriors",
    "descripcion": "No artes marciales."
}

### Recuperar los subcategorias
GET http://localhost:3000/api/subcategorias
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2RjMTUzMTI4MDYxYzAyNWM1ZWU5YzgiLCJpYXQiOjE2NzU2NDQ5NzYsImV4cCI6MTY3NTY4ODE3Nn0.6PllQgH1N6kSyHSuF7_CDUXQ7Q35OUohIMzwgtIeSjs


### Crear subcategorias
POST http://localhost:3000/api/subcategorias
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UwNTQ4NjAwMDI3YzczMDdmZmNmM2MiLCJpYXQiOjE2NzU2NDYxMDIsImV4cCI6MTY3NTY4OTMwMn0.sLFjqpID7KqxeeTpkJa5KrbrWPMHbbKaT4QcG0WdOfw
Content-Type: application/json

{
    "nombre": "ExTreme",
    "descripcion": "Programa para competir Extreme."
}

### Recuperar los Clientes
GET http://localhost:3000/api/clientes
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UxMjZlNDgyOTI1NzcyYzM1MWMzZTQiLCJpYXQiOjE2NzU2OTk5ODMsImV4cCI6MTY3NTc0MzE4M30.gTXfuHvv2QvDQ4dOTU7MD3oKySQNQCPRwUSkDkshjiU


### Crear Cliente
POST http://localhost:3000/api/clientes
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UxMjZlNDgyOTI1NzcyYzM1MWMzZTQiLCJpYXQiOjE2NzU2OTk5ODMsImV4cCI6MTY3NTc0MzE4M30.gTXfuHvv2QvDQ4dOTU7MD3oKySQNQCPRwUSkDkshjiU
Content-Type: application/json

{
    "rut": "1234",
    "nombres": "pedro",
    "apellidos": "gomez"
}

### Subir Imagen Cliente
PUT http://localhost:3000/api/uploads/clientes/63e1296e53a602b8a3fcc4ee
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="MeLlamoPacPat.png"
Content-Type: image/png

< C:\Users\gchavez\Pictures\MeLlamoPacPat.png
--MfnBoundry--

### Recuperar los Empleados
GET http://localhost:3000/api/empleados
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UxMjZlNDgyOTI1NzcyYzM1MWMzZTQiLCJpYXQiOjE2NzU2OTk5ODMsImV4cCI6MTY3NTc0MzE4M30.gTXfuHvv2QvDQ4dOTU7MD3oKySQNQCPRwUSkDkshjiU


### Crear Empleado
POST http://localhost:3000/api/empleados
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UxMjZlNDgyOTI1NzcyYzM1MWMzZTQiLCJpYXQiOjE2NzU2OTk5ODMsImV4cCI6MTY3NTc0MzE4M30.gTXfuHvv2QvDQ4dOTU7MD3oKySQNQCPRwUSkDkshjiU
Content-Type: application/json

{
    "rut": "1234",
    "nombres": "pedro",
    "apellidos": "gomez"
}


### Subir Imagen Empleado
PUT http://localhost:3000/api/uploads/empleados/63e12a566e0777ece296a1b3
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="MeLlamoPacPat.png"
Content-Type: image/png

< C:\Users\gchavez\Pictures\MeLlamoPacPat.png
--MfnBoundry--


### Recuperar los Instructores
GET http://localhost:3000/api/instructores
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UwNTQ4NjAwMDI3YzczMDdmZmNmM2MiLCJpYXQiOjE2NzU3MDgxNjIsImV4cCI6MTY3NTc1MTM2Mn0.jTd6UazO04PAl7yzfIkg5tjVdZXCSrMefreyDqYsObM


### Crear Instructor
POST http://localhost:3000/api/instructores
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UwNTQ4NjAwMDI3YzczMDdmZmNmM2MiLCJpYXQiOjE2NzU3MDgxNjIsImV4cCI6MTY3NTc1MTM2Mn0.jTd6UazO04PAl7yzfIkg5tjVdZXCSrMefreyDqYsObM
Content-Type: application/json

{
    "rut": "1234",
    "nombres": "pedro",
    "apellidos": "gomez"
}


### Subir Imagen Instructor
PUT http://localhost:3000/api/uploads/instructores/63e12ae26e0777ece296a1ba
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UwNTQ4NjAwMDI3YzczMDdmZmNmM2MiLCJpYXQiOjE2NzU3MDgxNjIsImV4cCI6MTY3NTc1MTM2Mn0.jTd6UazO04PAl7yzfIkg5tjVdZXCSrMefreyDqYsObM
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="image"; filename="OIP.png"
Content-Type: image/*

< C:\Users\gchavez\Pictures\OIP.png
--MfnBoundry--


### Mostrar Imagen Instructor
GET http://localhost:3000/api/uploads/instructores/df6240f7-f86b-437c-a2c4-52d3fced2482.png


### Mostrar Imagen Instructor
POST http://localhost:3000/api/login/google/
Content-Type: application/json

{
    "token": "123"
}


### Renovar token
GET http://localhost:3000/api/login/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2UxMjZlNDgyOTI1NzcyYzM1MWMzZTQiLCJpYXQiOjE2NzU3ODQyMzYsImV4cCI6MTY3NTgyNzQzNn0.GutsNIjLHXUeLi-Ca9f8PV3pwWRIsBI6WyZLH_0ubLc